{
	"version": 1557493867,
	"fileList": [
		"data.js",
		"game.html",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/backgroundtile.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/standardplatform.png",
		"images/movingsolidtile.png",
		"images/jumpthroughplatform.png",
		"images/movingplatform.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/startback.png",
		"images/logo-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/tiledbackground10.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/solidtile2.png",
		"images/levelback.png",
		"images/backgroundtutorial.png",
		"images/controls-sheet0.png",
		"images/cat-sheet0.png",
		"images/anvil-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/tiledbackground16.png",
		"images/movingsolidtile3.png",
		"images/levelback2.png",
		"images/memcard2-sheet0.png",
		"images/memcard2-sheet1.png",
		"images/memcard2-sheet2.png",
		"images/memcard1-sheet0.png",
		"images/memcard1-sheet1.png",
		"images/memcard1-sheet2.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/fireworks.png",
		"images/bloodcat.png",
		"images/sprite25-sheet0.png",
		"images/pegi18-sheet0.png",
		"images/menuhamster-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/hanleydevelopment-sheet0.png",
		"images/c2logo-sheet0.png",
		"images/tiledbackground5.png",
		"images/eagle-sheet0.png",
		"images/eagle-sheet1.png",
		"images/eagleblood.png",
		"images/sprite12-sheet0.png",
		"images/blackcanvas-sheet0.png",
		"images/tiledbackground7.png",
		"images/purplecanvas-sheet0.png",
		"images/lvl1-sheet0.png",
		"images/lvl2-sheet0.png",
		"images/sprite38-sheet0.png",
		"images/lvl3-sheet0.png",
		"images/lvl3-sheet1.png",
		"images/lvl4-sheet0.png",
		"images/lvl4-sheet1.png",
		"images/lvl5-sheet0.png",
		"images/lvl5-sheet1.png",
		"images/lvl6-sheet0.png",
		"images/lvl6-sheet1.png",
		"images/lives-sheet0.png",
		"images/tiledbackground11.png",
		"images/cage.png",
		"images/tiledbackground15.png",
		"images/tiledbackground17.png",
		"images/backgroundtutorial2.png",
		"images/tiledbackground6.png",
		"images/requirements-sheet0.png",
		"images/requirements-sheet1.png",
		"images/requirements-sheet2.png",
		"images/sprite26-sheet0.png",
		"images/particles.png",
		"images/tiledbackground18.png",
		"images/sky-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/tiledbackground20.png",
		"images/tiledbackground21.png",
		"images/particles2.png",
		"images/sprite13-sheet0.png",
		"images/tilemap.png",
		"images/tiledbackground22.png",
		"images/tiledbackground23.png",
		"images/sprite33-sheet0.png",
		"images/sprite34-sheet0.png",
		"media/hamsterhavoc.m4a",
		"media/hamsterhavoc.ogg",
		"media/level 2.m4a",
		"media/level 2.ogg",
		"media/hanley development.m4a",
		"media/hanley development.ogg",
		"media/level 3.m4a",
		"media/level 3.ogg",
		"media/level 4.m4a",
		"media/level 5.m4a",
		"media/level 6.m4a",
		"media/finale.m4a",
		"media/level 5.ogg",
		"media/level 4 .ogg",
		"media/level 6.ogg",
		"media/my song 22.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"start.webm",
		"start.ogv",
		"start.mp4",
		"credits.webm",
		"credits.ogv",
		"credits.mp4",
		"Amazon-Web-App-API.min.js",
		"Amazon-Web-App-API-tester.min.js",
		"tizen-iap.js",
		"cws-buy.js"
	]
}